# Generated by Django 3.1.1 on 2020-10-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlisting_bid_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='startingBid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
